# Generated by Django 4.2.11 on 2024-10-09 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_booking_payment_id_booking_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='payment_id',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='status',
        ),
    ]
